Repository marcusolsson/obsidian-projects, pull requests merged in 2023-10, with the labels that each got.

#693 Archive and restore projects
  src/lib/stores/settings.ts
  src/lib/stores/translations/en.json
  src/lib/stores/translations/zh-CN.json
  src/main.ts
  src/settings/settings.test.ts
  src/settings/settings.ts
  src/settings/v2/settings.test.ts
  src/settings/v2/settings.ts
  src/ui/app/toolbar/ProjectSelect.svelte
  src/ui/modals/components/CreateProject.svelte
  src/ui/modals/components/EditNote.svelte
  src/ui/settings/Archives.svelte
  src/ui/settings/Projects.svelte
  src/ui/settings/settings.ts
Labels: kind/feature

#700 Open in new window via view's more-options list
  src/view.ts
Labels: kind/enhancement

#679 Aligning field type icons with the Properties for consistency
  src/lib/stores/translations/en.json
  src/lib/stores/translations/zh-CN.json
  src/main.ts
  src/ui/views/Table/components/DataGrid/GridHeader.svelte
  src/ui/views/Table/components/DataGrid/GridHeader/GridColumnHeader.svelte
  src/ui/views/Table/components/DataGrid/dataGrid.ts
  src/ui/views/helpers.ts
Labels: kind/enhancement

#708 Fixed english string resources (EN)
  src/lib/stores/translations/en.json
Labels: kind/enhancement

#642 Fix Enter to close new note modal
  src/ui/modals/components/CreateNote.svelte
Labels: kind/bug

#713 Checking if a file is included in a subfolder correctly
  src/lib/datasources/folder/datasource.ts
Labels: kind/bug, area/datasource/frontmatter

#686 Filtering list / multi-select fields
  src/settings/base/settings.ts
  src/ui/app/filterFunctions.ts
  src/ui/app/toolbar/viewOptions/color/ColorOptions.svelte
  src/ui/app/toolbar/viewOptions/color/helpers.ts
  src/ui/app/toolbar/viewOptions/filter/FilterOptions.svelte
  src/ui/app/toolbar/viewOptions/filter/helpers.ts
  src/ui/components/TagsInput/Tag/Tag.svelte
  src/ui/components/TagsInput/Tag/index.ts
  src/ui/components/TagsInput/TagInput/TagInput.svelte
  src/ui/components/TagsInput/TagInput/index.ts
  src/ui/components/TagsInput/TagsInput.svelte
  src/ui/components/TagsInput/index.ts
Labels: kind/feature

#687 Fix sorting empty values
  src/ui/app/viewSort.test.ts
  src/ui/app/viewSort.ts
Labels: kind/bug

#691 Filtering dates
  src/settings/base/settings.ts
  src/ui/app/filterFunctions.ts
  src/ui/app/toolbar/viewOptions/color/ColorOptions.svelte
  src/ui/app/toolbar/viewOptions/color/helpers.ts
  src/ui/app/toolbar/viewOptions/filter/FilterOptions.svelte
  src/ui/app/toolbar/viewOptions/filter/helpers.ts
Labels: kind/feature
