Repository marcusolsson/obsidian-projects, pull requests merged in 2023-04, with the labels that each got.

#490 Update obsidian-svelte
  package-lock.json
  package.json
  src/app/toolbar/ProjectSelect.svelte
  src/app/toolbar/ViewItem.svelte
  src/components/FileListInput/FileListInput.svelte
  src/components/FilterSettings/ColorFilterSettings.svelte
  src/components/FilterSettings/FilterSettings.svelte
  src/components/MultiTextInput/MultiTextInput.svelte
  src/components/TagList/TagList.svelte
  src/modals/components/Inspector.svelte
  src/views/Board/BoardView.svelte
  src/views/Calendar/components/Navigation/Navigation.svelte
  src/views/Gallery/GalleryView.svelte
  src/views/Table/components/DataGrid/GridHeader.svelte
  src/views/Table/components/DataGrid/GridHeader/GridColumnHeader.svelte
Labels: kind/cleanup

#468 New toolbar design
  src/app/toolbar/ProjectSelect.svelte
  src/app/toolbar/Toolbar.svelte
  src/app/toolbar/ViewSelect.svelte
  src/lib/stores/i18n.ts
  src/views/Board/components/Board/BoardColumn.svelte
  src/views/Gallery/GalleryView.svelte
  src/views/Gallery/gallery-view.ts
Labels: kind/enhancement

#491 Clean up toolbar slots
  src/app/toolbar/Toolbar.svelte
  src/components/Layout/ViewToolbar.svelte
Labels: kind/cleanup

#492 Bump version
  manifest.json
  package.json
Labels: ignore-for-release

#495 Remove lookbehind regex
  manifest.json
  src/lib/metadata/decode.test.ts
  src/lib/metadata/decode.ts
Labels: kind/bug

#496 Bump version
  manifest.json
  package.json
Labels: ignore-for-release

#504 Fixes Create note on tag view
  src/lib/filesystem/obsidian/obsidian.ts
Labels: kind/bug

#514 Upgrade dependencies
  package-lock.json
Labels: kind/cleanup

#516 Bump version
  manifest.json
  package.json
Labels: ignore-for-release

#517 Update package-lock.json
  package-lock.json
Labels: ignore-for-release

#518 Update GitHub Actions workflow
  .github/workflows/release.yml
Labels: kind/cleanup

#519 Update GitHub Actions
  .github/workflows/release.yml
Labels: ignore-for-release

#521 Smooth resize when moving cards
  src/views/Board/components/Board/CardGroup.svelte
Labels: kind/enhancement

#524 Simplify GitHub Actions workflow
  .github/workflows/release.yml
Labels: kind/cleanup

#526 Test new GitHub Action
  .github/workflows/release.yml
Labels: ignore-for-release

#527 Fix GitHub Action error
  .github/workflows/release.yml
Labels: ignore-for-release

#528 Test actions
  .github/workflows/release.yml
Labels: ignore-for-release

#531 Test GitHub Actions
  .github/workflows/release.yml
Labels: ignore-for-release

#532 Test GitHub Action
  .github/workflows/release.yml
Labels: ignore-for-release

#533 Update GitHub Actions
  .github/workflows/release.yml
Labels: ignore-for-release

#541 Update README.md
  README.md
Labels: kind/documentation

#542 Bump version
  manifest.json
  package-lock.json
  package.json
Labels: ignore-for-release

#544 Add read-only label for Dataview projects
  src/app/toolbar/Flair.svelte
  src/app/toolbar/ProjectSelect.svelte
  src/lib/stores/i18n.ts
Labels: kind/enhancement

#545 Display help messages for calendar view
  src/views/Calendar/CalendarView.svelte
Labels: kind/enhancement

#546 Table: Enable Add note button for Dataview projects
  src/views/Table/components/DataGrid/DataGrid.svelte
Labels: kind/enhancement

#547 Add year to calendar interval
  src/views/Calendar/calendar.ts
Labels: kind/enhancement

#548 Bump version
  manifest.json
  package-lock.json
  package.json
Labels: ignore-for-release
