Repository marcusolsson/obsidian-projects, pull requests merged in 2023-11, with the labels that each got.

#718 Improve i18n
  src/lib/stores/translations/en.json
  src/lib/stores/translations/zh-CN.json
  src/ui/settings/Archives.svelte
  src/ui/settings/settings.ts
  src/ui/views/Calendar/calendar.ts
Labels: kind/enhancement

#719 Bump version
  manifest.json
  package-lock.json
  package.json
Labels: ignore-for-release

#723 Better visual hint when add-note button is focused
  src/ui/views/Board/components/Board/BoardColumn.svelte
  src/ui/views/Table/components/DataGrid/DataGrid.svelte
Labels: kind/enhancement

#721 Fix i18n issue with year value on calendar heading
  src/lib/stores/translations/en.json
  src/lib/stores/translations/zh-CN.json
  src/ui/views/Calendar/calendar.ts
Labels: kind/bug

#722 Fix board column width reactivity
  src/ui/views/Board/BoardOptionsProvider.svelte
  src/ui/views/Board/BoardView.svelte
Labels: kind/bug

#724 Relax tagsinput validation
  src/ui/app/toolbar/viewOptions/color/ColorOptions.svelte
  src/ui/app/toolbar/viewOptions/filter/FilterOptions.svelte
  src/ui/components/TagsInput/TagsInput.svelte
Labels: kind/enhancement

#725 Improve i18n
  src/lib/stores/translations/en.json
  src/lib/stores/translations/zh-CN.json
  src/ui/components/TagsInput/Tag/Tag.svelte
Labels: kind/enhancement

#735 Bump version
  manifest.json
  package-lock.json
  package.json
Labels: ignore-for-release

#736 Update tsconfig
  tsconfig.json
Labels: ignore-for-release

#737 Add video and article contributors
  README.md
Labels: kind/documentation
