Repository marcusolsson/obsidian-projects, pull requests merged in 2023-01, with the labels that each got.

#294 Add workflow for stale issues
  .github/workflows/stale.yml
Labels: ignore-for-release

#295 Add manual trigger for stale workflow
  .github/workflows/stale.yml
Labels: ignore-for-release

#297 Update stale.yml
  .github/workflows/stale.yml
Labels: ignore-for-release

#301 Update maintenance status link
  README.md
Labels: kind/documentation

#302 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: kind/documentation

#305 Remove issue template for support requests
  .github/ISSUE_TEMPLATE/support-request.yml
Labels: kind/documentation

#306 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: kind/documentation

#310 Update README.md
  README.md
Labels: kind/documentation

#311 Update README.md
  README.md
Labels: kind/documentation

#312 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: kind/documentation

#317 Apply default field sorting
  src/lib/datasources/dataview/dataview.ts
  src/lib/datasources/frontmatter/frontmatter.ts
  src/views/Table/TableView.svelte
  src/views/Table/components/DataGrid/DataGrid.svelte
  src/views/Table/components/DataGrid/data-grid.ts
Labels: kind/bug

#319 Table: Rich text support for text fields
  src/lib/datasources/helpers.ts
  src/views/Table/components/DataGrid/GridCell/GridTextCell/TextInput.svelte
  src/views/Table/components/DataGrid/GridCell/GridTextCell/TextLabel.svelte
Labels: kind/feature, area/view/table

#321 Add config for ordering table columns
  src/views/Table/TableView.svelte
  src/views/Table/helpers.test.ts
  src/views/Table/helpers.ts
  src/views/Table/types.ts
Labels: kind/feature

#322 Bump version
  manifest.json
  package.json
Labels: ignore-for-release

#323 Add settings for rich text and link detection
  src/app/AppContainer.svelte
  src/lib/data.ts
  src/lib/datasources/dataview/dataview.ts
  src/lib/datasources/frontmatter/frontmatter-helpers.test.ts
  src/lib/datasources/frontmatter/frontmatter-helpers.ts
  src/lib/datasources/frontmatter/frontmatter.ts
  src/lib/stores/settings.ts
  src/main.ts
  src/modals/components/ConfigureField.svelte
  src/settings.ts
  src/types.ts
  src/views/Table/components/DataGrid/GridCell/GridTextCell/GridTextCell.svelte
  src/views/Table/components/DataGrid/GridCell/GridTextCell/TextLabel.svelte
Labels: kind/feature

#324 Gallery View: Configure card width
  src/views/Gallery/GalleryView.svelte
  src/views/Gallery/components/Grid/Grid.svelte
  src/views/Gallery/settings/GallerySettings.svelte
  src/views/Gallery/settings/settings-modal.ts
  src/views/Gallery/types.ts
Labels: kind/feature, area/view/gallery

#328 Table: Add rich text formatting to Dataview projects
  src/components/FieldControl/FieldControl.svelte
  src/lib/data-api.ts
  src/lib/data.ts
  src/lib/datasources/dataview/dataview-helpers.ts
  src/lib/datasources/dataview/dataview.ts
  src/lib/datasources/frontmatter/frontmatter-helpers.test.ts
  src/lib/datasources/frontmatter/frontmatter-helpers.ts
  src/lib/datasources/frontmatter/frontmatter.ts
  src/lib/datasources/helpers.test.ts
  src/lib/datasources/helpers.ts
  src/lib/stores/i18n.ts
  src/main.ts
  src/modals/components/ConfigureField.svelte
  src/modals/configure-field.ts
  src/settings.ts
  src/views/Gallery/GalleryView.svelte
  src/views/Table/TableView.svelte
  src/views/Table/components/DataGrid/DataGrid.svelte
  src/views/Table/components/DataGrid/GridCell/GridLinkCell/GridLinkCell.svelte
  src/views/Table/components/DataGrid/GridCell/GridLinkCell/LinkLabel.svelte
  src/views/Table/components/DataGrid/GridCell/GridLinkCell/index.ts
  src/views/Table/components/DataGrid/GridCell/GridTypedCell.svelte
  src/views/Table/components/DataGrid/GridRow.svelte
  src/views/Table/components/DataGrid/data-grid.ts
  src/views/helpers.ts
Labels: kind/feature, area/view/table

#330 Set auto placement for filter popovers
  src/app/toolbar/Toolbar.svelte
Labels: kind/bug

#337 Gallery: Parse links in text fields
  src/views/Gallery/GalleryView.svelte
  src/views/Gallery/helpers.test.ts
  src/views/Gallery/helpers.ts
Labels: kind/bug, priority/critical, area/view/gallery

#329 Display project name when deleting project
  src/app/toolbar/ProjectSelect.svelte
  src/lib/stores/i18n.ts
Labels: kind/feature

#338 Add logo design
  images/dark.svg
  images/light.svg
Labels: kind/documentation

#339 Convert images to curves
  images/dark.svg
  images/light.svg
Labels: kind/documentation

#340 Update README.md
  README.md
Labels: kind/documentation

#341 Bump version
  manifest.json
  package.json
Labels: ignore-for-release

#342 Fix logo fallback
  README.md
Labels: kind/documentation

#343 Bump version
  manifest.json
  package.json
Labels: ignore-for-release

#344 Fix README
  README.md
Labels: kind/documentation

#345 Bump version
  manifest.json
  package.json
Labels: ignore-for-release

#346 Fix README (again)
  README.md
  assets/board.png
  assets/calendar.png
  assets/table.png
  images/dark.svg
  images/light.svg
  manifest.json
  package.json
Labels: kind/documentation

#348 Add project size limit
  src/lib/datasources/frontmatter/frontmatter.ts
  src/lib/datasources/helpers.ts
  src/main.ts
  src/settings.ts
Labels: kind/feature

#349 Add new Tag data source
  obsidian-projects-types/index.ts
  obsidian-projects-types/package.json
  src/app/AppContainer.svelte
  src/app/View.svelte
  src/app/filter-functions.ts
  src/app/onboarding/demo-project.ts
  src/app/toolbar/ProjectSelect.svelte
  src/app/toolbar/Toolbar.svelte
  src/app/toolbar/ViewSelect.svelte
  src/app/useView.ts
  src/components/Accordion/AccordionItem.svelte
  src/components/Accordion/index.ts
  src/components/FilterSettings/ColorFilterSettings.svelte
  src/components/FilterSettings/FilterSettings.svelte
  src/custom-view-api.ts
  src/events.ts
  src/lib/data-api.ts
  src/lib/data.ts
  src/lib/datasources/dataview/dataview.ts
  src/lib/datasources/folder/folder.ts
  src/lib/datasources/frontmatter/frontmatter.ts
  src/lib/datasources/tag/tag.ts
  src/lib/helpers.ts
  src/lib/stores/i18n.ts
  src/lib/stores/settings.ts
  src/main.ts
  src/modals/add-view-modal.ts
  src/modals/components/AddView.svelte
  src/modals/components/CreateNote.svelte
  src/modals/components/CreateProject.svelte
  src/modals/create-note-modal.ts
  src/modals/create-project-modal.ts
  src/settings.ts
  src/settings/base/settings.ts
  src/settings/settings.test.ts
  src/settings/settings.ts
  src/settings/v1/settings.test.ts
  src/settings/v1/settings.ts
  src/settings/v2/settings.test.ts
  src/settings/v2/settings.ts
  src/views/Board/BoardView.svelte
  src/views/Calendar/CalendarView.svelte
  src/views/Table/TableView.svelte
Labels: kind/feature, area/view/custom, area/datasources

#357 Bump version
  manifest.json
  package.json
Labels: ignore-for-release

#370 Prevent queries to run when updating views
  src/app/App.svelte
  src/app/AppContainer.svelte
  src/app/DataFrameProvider.svelte
  src/views/Board/BoardView.svelte
  src/views/Calendar/CalendarView.svelte
  src/views/Gallery/GalleryView.svelte
  src/views/Table/TableView.svelte
Labels: kind/bug

#371 Resolve preferences in settings
  src/settings/v2/settings.ts
Labels: kind/bug

#373 Include tags in front matter
  src/lib/datasources/tag/tag.ts
Labels: kind/bug

#374 Table: Use ids for each blocks
  src/app/toolbar/ViewSelect.svelte
  src/components/CardMetadata/CardMetadata.svelte
  src/modals/components/EditNote.svelte
  src/views/Gallery/GalleryView.svelte
  src/views/Table/components/DataGrid/DataGrid.svelte
  src/views/Table/components/DataGrid/GridHeader.svelte
  src/views/Table/components/DataGrid/GridRow.svelte
Labels: kind/bug

#376 Bump version
  manifest.json
  package.json
Labels: ignore-for-release

#382 Update release.yml
  .github/release.yml
Labels: ignore-for-release

#379 Fix boolean field merge issue
  src/lib/stores/dataframe.ts
Labels: kind/bug

#381 Extend card color to full height
  src/components/CardMetadata/CardMetadata.svelte
  src/components/CardMetadata/Text.svelte
  src/components/ColorItem/ColorItem.svelte
  src/views/Board/components/Board/CardGroup.svelte
  src/views/Gallery/GalleryView.svelte
Labels: area/view/board, area/view/gallery

#384 Switch from yarn to NPM
  .github/workflows/ci.yml
  .github/workflows/release.yml
  package-lock.json
  yarn.lock
Labels: kind/cleanup

#385 Fix linter errors
  src/views/Board/components/Board/CardGroup.svelte
Labels: kind/cleanup

#386 Bump version
  manifest.json
  package.json
Labels: ignore-for-release

#388 Fix CSS issue
  src/components/ColorItem/ColorItem.svelte
Labels: kind/bug

#389 Bump version
  manifest.json
  package.json
Labels: ignore-for-release

#391 Support the tag front matter property
  src/lib/datasources/tag/tag.ts
Labels: kind/bug

#392 Bump version
  manifest.json
  package.json
Labels: ignore-for-release

#393 Prevent table navigation when editing
  src/views/Table/components/DataGrid/GridCell/GridCell.svelte
Labels: kind/bug

#394 Bump version
  manifest.json
  package.json
Labels: ignore-for-release

#395 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: kind/documentation

#396 Table: Make row numbers sticky
  package-lock.json
  src/views/Table/components/DataGrid/GridCell/GridCell.svelte
Labels: area/view/table, kind/enhancement

#397 Clarify keyboard navigation
  src/views/Table/components/DataGrid/DataGrid.svelte
Labels: kind/cleanup

#404 Filter null values from tags front matter
  src/lib/datasources/tag/tag.ts
Labels: kind/bug, area/datasource/frontmatter

#405 Clarify template variable format
  src/lib/stores/i18n.ts
Labels: kind/documentation

#406 Add file system abstraction
  src/app/App.svelte
  src/app/DataFrameProvider.svelte
  src/app/onboarding/onboarding-modal.ts
  src/events.ts
  src/lib/data-api.ts
  src/lib/data.ts
  src/lib/datasources/dataview/dataview.ts
  src/lib/datasources/folder/folder.ts
  src/lib/datasources/frontmatter/frontmatter.ts
  src/lib/datasources/tag/tag.ts
  src/lib/filesystem/filesystem.ts
  src/lib/filesystem/inmem/inmem.ts
  src/lib/filesystem/obsidian/obsidian.ts
  src/lib/stores/api.ts
  src/lib/stores/fileSystem.ts
  src/lib/view-api.ts
  src/main.ts
Labels: kind/cleanup

#407 Add installation instructions
  README.md
Labels: kind/documentation
