Repository marcusolsson/obsidian-projects, pull requests merged in 2023-03, with the labels that each got.

#453 Upgrade obsidian dependency
  package-lock.json
Labels: kind/cleanup

#455 Fix useMarkdown action
  src/lib/datasources/folder/folder.ts
  src/views/Table/components/DataGrid/GridCell/GridCell.svelte
  src/views/Table/components/DataGrid/GridCell/GridTextCell/TextLabel.svelte
Labels: kind/bug

#458 Allow note creation without Status set
  src/views/Board/BoardView.svelte
Labels: kind/bug

#459 Add commands to show projects and views
  src/app/App.svelte
  src/app/View.svelte
  src/app/toolbar/ProjectSelect.svelte
  src/app/toolbar/Toolbar.svelte
  src/app/toolbar/ViewSelect.svelte
  src/custom-view-api.ts
  src/lib/stores/settings.ts
  src/main.ts
  src/modals/add-view-modal.ts
  src/modals/components/AddView.svelte
  src/obsidian-projects.d.ts
  src/settings.ts
  src/settings/base/settings.ts
  src/settings/settings.test.ts
  src/settings/v1/settings.test.ts
  src/settings/v1/settings.ts
  src/settings/v2/settings.test.ts
  src/settings/v2/settings.ts
  src/view.ts
Labels: kind/feature

#461 Update README.md
  README.md
Labels: kind/documentation

#467 Add place holder for new project path
  src/modals/components/CreateProject.svelte
Labels: kind/enhancement

#469 Refactor Show commands
  src/main.ts
  src/obsidian-projects.d.ts
Labels: kind/enhancement

#472 Bump version
  manifest.json
  package.json
Labels: ignore-for-release

#477 Improve documentation for configure field modal
  package-lock.json
  package.json
  src/modals/components/ConfigureField.svelte
Labels: kind/documentation

#488 Reorder columns
  src/views/Table/TableView.svelte
  src/views/Table/components/DataGrid/DataGrid.svelte
  src/views/Table/components/DataGrid/GridCell/Resizer.svelte
  src/views/Table/components/DataGrid/GridHeader/GridColumnHeader.svelte
  src/views/Table/components/DataGrid/GridHeader/GridHeader.svelte
Labels: kind/feature, area/view/table
