Repository marcusolsson/obsidian-projects, pull requests merged in 2024-05, with the labels that each got.

#861 Only modify field config options if the renaming column is pinned
  src/ui/views/Board/BoardView.svelte
Labels: kind/bug, area/view/board

#870 Fix table name link
  src/lib/datasources/frontmatter/datasource.ts
  src/ui/app/viewSort.ts
Labels: kind/bug

#872 Fix table column header alignment and expand toolbar
  src/ui/components/Layout/ViewToolbar.svelte
  src/ui/views/Table/components/DataGrid/GridHeader.svelte
  src/ui/views/Table/components/DataGrid/GridHeader/GridHeader.svelte
Labels: kind/bug

#876 Update to use ES2022
  tsconfig.json
Labels: kind/enhancement

#877 Add support for configuring first day of the week
  esbuild.config.mjs
  src/lib/stores/settings.ts
  src/lib/stores/translations/en.json
  src/obsidianProjects.d.ts
  src/settings/base/settings.ts
  src/settings/settings.test.ts
  src/settings/settings.ts
  src/settings/v1/settings.test.ts
  src/settings/v1/settings.ts
  src/settings/v2/settings.test.ts
  src/settings/v2/settings.ts
  src/ui/settings/settings.ts
  src/ui/views/Calendar/CalendarView.svelte
  src/ui/views/Calendar/calendar.ts
Labels: kind/feature

#879 Update / remove dependency
  package-lock.json
  package.json
Labels: kind/cleanup

#880 Utilize / fix DateInput component
  src/ui/app/toolbar/viewOptions/color/ColorOptions.svelte
  src/ui/app/toolbar/viewOptions/filter/FilterOptions.svelte
  src/ui/components/FieldControl/FieldControl.svelte
  src/ui/modals/components/CreateField.svelte
  src/ui/views/Table/components/DataGrid/GridCell/GridDateCell/GridDateCell.svelte
Labels: kind/bug, kind/enhancement

#883 Add beta workflow
  .github/workflows/ci.yml
  version-beta-manifest.mjs
Labels: ignore-for-release

#885 Improve code docs and tests
  .eslintrc.json
  package-lock.json
  package.json
  src/lib/datasources/folder/datasource.ts
  src/lib/datasources/helpers.test.ts
  src/lib/datasources/helpers.ts
  src/lib/datasources/index.ts
  src/lib/helpers.ts
  src/lib/metadata/encode.ts
  src/lib/templates/interpolate.ts
  src/ui/app/viewSort.ts
  src/ui/views/Board/board.ts
Labels: ignore-for-release
