Repository marcusolsson/obsidian-projects, pull requests merged in 2024-03, with the labels that each got.

#788 Add board custom card order
  src/customViewApi.ts
  src/lib/datasources/helpers.ts
  src/lib/helpers.ts
  src/lib/stores/translations/en.json
  src/lib/stores/translations/zh-CN.json
  src/ui/app/View.svelte
  src/ui/app/onboarding/demoProject.ts
  src/ui/app/toolbar/viewOptions/color/ColorOptions.svelte
  src/ui/app/useView.ts
  src/ui/app/viewSort.ts
  src/ui/views/Board/BoardOptionsProvider.svelte
  src/ui/views/Board/BoardView.svelte
  src/ui/views/Board/board.ts
  src/ui/views/Board/boardView.ts
  src/ui/views/Board/components/Board/Board.svelte
  src/ui/views/Board/components/Board/BoardColumn.svelte
  src/ui/views/Board/components/Board/CardList.svelte
  src/ui/views/Board/components/Board/types.ts
  src/ui/views/Board/settings/BoardSettings.svelte
  src/ui/views/Board/settings/settingsModal.ts
  src/ui/views/Board/types.ts
  src/ui/views/Calendar/CalendarView.svelte
  src/ui/views/Calendar/components/Calendar/EventList.svelte
  src/ui/views/Table/components/SwitchSelect/SwitchSelect.svelte
  src/ui/views/helpers.ts
  styles.css
Labels: kind/feature, area/view/board

#782 feat: add fink localization editor
  README.md
  project.inlang/project_id
  project.inlang/settings.json
Labels: kind/feature

#769 Update typo in README.md
  README.md
Labels: lifecycle/stale

#811 Update docs
  CONTRIBUTING.md
  README.md
  src/ui/app/onboarding/Onboarding.svelte
Labels: kind/documentation

#814 Allow rich text rendering for list tags
  src/ui/components/TagList/TagList.svelte
  src/ui/modals/components/ConfigureField.svelte
  src/ui/views/Table/components/DataGrid/GridCell/GridListCell/GridListCell.svelte
  src/ui/views/Table/components/DataGrid/GridCell/GridListCell/RichTextTag.svelte
Labels: kind/enhancement

#815 Fix hover on link in a table row
  src/ui/views/Table/components/DataGrid/GridRow.svelte
Labels: kind/bug, area/view/table

#818 Board: header overflow, column orders, and clean up column configs
  src/ui/views/Board/BoardOptionsProvider.svelte
  src/ui/views/Board/BoardView.svelte
  src/ui/views/Board/board.ts
  src/ui/views/Board/components/Board/ColumnHeader.svelte
Labels: kind/enhancement

#819 Bump version
  manifest.json
  package-lock.json
  package.json
Labels: ignore-for-release

#823 Fix non-folder based project won't listen to file deletion
  src/events.ts
Labels: kind/bug, area/datasources

#824 Pin (lock, freeze) table columns
  src/lib/stores/translations/en.json
  src/lib/stores/translations/zh-CN.json
  src/ui/views/Table/TableView.svelte
  src/ui/views/Table/components/DataGrid/DataGrid.svelte
  src/ui/views/Table/components/DataGrid/GridCell/GridCell.svelte
  src/ui/views/Table/components/DataGrid/GridHeader/GridColumnHeader.svelte
  src/ui/views/Table/components/DataGrid/GridHeader/GridHeader.svelte
  src/ui/views/Table/components/DataGrid/dataGrid.ts
  src/ui/views/Table/types.ts
Labels: kind/feature, area/view/table

#826 Always conduct numeric locale compare between strings
  src/lib/datasources/dataview/datasource.ts
  src/lib/datasources/frontmatter/datasource.ts
  src/ui/views/Board/board.ts
Labels: kind/cleanup

#827 Board: Remove prioritize helpers and tests
  src/ui/views/Board/components/Board/boardHelpers.test.ts
  src/ui/views/Board/components/Board/boardHelpers.ts
Labels: kind/cleanup
