Repository marcusolsson/obsidian-projects, pull requests merged in 2024-07, with the labels that each got.

#924 Fix calculation of month range
  src/ui/views/Calendar/calendar.ts
Labels: kind/bug

#913 Ukrainian translation
  src/lib/stores/i18n.ts
  src/lib/stores/translations/uk.json
Labels: kind/enhancement

#919 Handle cleared date-input value
  src/ui/components/FieldControl/FieldControl.svelte
  src/ui/modals/components/CreateField.svelte
  src/ui/views/Table/components/DataGrid/GridCell/GridDateCell/GridDateCell.svelte
Labels: kind/bug

#921 Added a filter option to search for parts of entries contained in lists
  src/settings/base/settings.ts
  src/ui/app/filterFunctions.ts
  src/ui/app/toolbar/viewOptions/color/ColorOptions.svelte
  src/ui/app/toolbar/viewOptions/color/helpers.ts
  src/ui/app/toolbar/viewOptions/filter/FilterOptions.svelte
  src/ui/app/toolbar/viewOptions/filter/helpers.ts
Labels: kind/enhancement, area/filtering

#925 Add hint on new column button when no status field assigned
  src/lib/stores/translations/en.json
  src/lib/stores/translations/uk.json
  src/lib/stores/translations/zh-CN.json
  src/ui/views/Board/BoardView.svelte
  src/ui/views/Board/components/Board/Board.svelte
  src/ui/views/Board/components/Board/NewColumn.svelte
Labels: area/view/board, kind/enhancement

#926 Bump version
  manifest.json
  package-lock.json
  package.json
Labels: ignore-for-release
